### ISSUE TITLE
Actionbars being skinned even if disabled

### ISSUE THREAD

**Issue by Jeirs** [greven/LumUI#2]
![Screenshot_1](https://user-images.githubusercontent.com/23572961/100296858-a810df80-2fbb-11eb-97d0-77886425600b.png)

![Screenshot_5](https://user-images.githubusercontent.com/23572961/100296886-bb23af80-2fbb-11eb-9ce7-b59276a0232f.png)

I am using LortiUI to skin my actionbars , so I disabled the module but the bars are still being skinned

**Comment by Jeirs** [comment]
![Screenshot_6](https://user-images.githubusercontent.com/23572961/100296994-03db6880-2fbc-11eb-93cc-1ca5a8893a40.png)

**Comment by greven** [comment]
Hey. Thanks for reporting this.
Those settings I need to disable as... most are not working since I started implementing graphical settings years ago but never actually finished. 
I do intend to come back to LumUI to give it a pass now that I'm mostly done with oUF_Lumen (other than the RAID frames which are still WIP).

Thx for the bug issue.

I'm going to push an update for you to be able to disable them using config.lua. Leaving a commented example there to do it, just need to uncomment that line. :)

https://github.com/greven/LumUI/commit/788a0634c3b781735fb97d85098b13a74cd2376f

Will mark this as closed for now, since this solves it, doesn't address the graphical settings, which to be honest I do intend to remove as they are a lot of work to do and never actually fully implemented them... as you can see. 😄

**Comment by greven** [comment]
https://github.com/greven/LumUI/commit/788a0634c3b781735fb97d85098b13a74cd2376f
